services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_THEME: keycloak
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: 8085
      KC_HOSTNAME: https://ominous-acorn-jq79964gg7gc55rj-8085.app.github.dev/ 
      QUARKUS_DATASOURCE_JDBC_POOL_SIZE: 20
    ports:
      - 8085:8085
    depends_on:
      - db
    volumes:
      - ./realm-export:/opt/keycloak/data/import/export.json # optional, for realm imports.
    networks:
      - gn-network

  db:
   image: postgres:13
   environment:
     POSTGRES_USER: keycloak
     POSTGRES_PASSWORD: password
     POSTGRES_DB: keycloak 
   volumes:
     - ./db-data:/var/lib/postgresql/data
   ports:
     - 5432:5432 # optional, only if you want to access the db directly from your host.
   networks:
     - gn-network

volumes:
  db-data:

networks:
  gn-network:
    driver: bridge